### ISSUE TITLE
de-boostify

### ISSUE THREAD

**Issue by cia48621793** [andrivet/ADVobfuscator#11]
The Boost Library is a terrible set of utter craps, can you really drop it in favor of STL?

**Comment by andrivet** [comment]
ADVobfuscator uses Boost only for the Finite State Machine part. And STL has no such component (and I doubt it will one day). An alternative would be to replace it by Hana (i.e. build the FSM part with Hana), but it is also now part of Boost. So no, for the moment, I have no plan to de-boostify ADVobfuscator.

**Comment by Amadeus-** [comment]
I would argue that the boost library is pretty good.   At the very least, it's certainly not something I would describe as "a terrible set of utter craps".

**Comment by andrivet** [comment]
Boost does contains some ugly code, macros, etc. mainly because it tries to be compatible with old compilers. But I agree. It can't be qualified as "a terrible set of utter craps". It is a great set of libraries and a laboratory for the Standard Library.
