### ISSUE TITLE
Function in class

### ISSUE THREAD

**Issue by alecs26** [andrivet/ADVobfuscator#15]
Hello,

First, I want to thank you for this amazing project and its ease of use.

My issue might in fact be a question coming from a lack of experience.

The functions I want to obfuscate are inside a class such as:
```
class Loop1 : public BaseThread
{
public:
    Loop1();
...
```
The problem with that is that when I call a function like     OBFUSCATED_CALL0(FaceToCursorPos)
I have an error (below). I tried different things without success.

> MetaFSM.h:162: error: invalid cast from type 'void (Loop1::*)()' to type 'andrivet::ADVobfuscator::ObfuscatedAddress

Thank you so much for your help.

**Comment by andrivet** [comment]
This feature is not implemented. Calling a member function is not the same as calling a function (with member function, you have an hidden parameter: this). I may implement this one day, but it is not in my priorities for the moment.
