### ISSUE TITLE
Alternative/Production ready function call obfuscation?

### ISSUE THREAD

**Issue by BullyWiiPlaza** [andrivet/ADVobfuscator#26]
Are there any plans on implementing an alternative function call obfuscation without requiring `Boost` and what about the production ready function call obfuscation with the function call being placed in the middle of the state machine you mentioned in the comment [here](https://github.com/andrivet/ADVobfuscator/blob/master/Lib/ObfuscatedCall.h#L28-L29)?

**Comment by andrivet** [comment]
> Are there any plans on implementing an alternative function call obfuscation without requiring Boost

No plan.

> what about the production ready function call obfuscation with the function call being placed in the middle of the state machine

I just gave an example. You can use the FSM you want.
