### ISSUE TITLE
Complied error with struct operator() called.

### ISSUE THREAD

**Issue by beizi8** [andrivet/ADVobfuscator#28]
// To remove Boost assert messages
#if !defined(DEBUG) || DEBUG == 0
#define BOOST_DISABLE_ASSERTS
#endif

#pragma warning(disable: 4503)

#include <iostream>
#include "MetaString.h"
#include "ObfuscatedCall.h"
#include "ObfuscatedCallWithPredicate.h"

using namespace andrivet::ADVobfuscator;
struct Function1 {
    inline void operator()(int a, int b) {
        cout << DEF_OBFUSCATED("Womenizer").decrypt() << endl;
    }
};
// Obfuscate function calls
void SampleFiniteStateMachine() {
    using namespace andrivet::ADVobfuscator::Machine1;
   OBFUSCATED_CALL(Function1 , 1, 2);
}

// Entry point
int main(int, const char *[]) {
    SampleFiniteStateMachine();
    return 0;
}

aboved code cannot complied with Visual Stdio 2015

**Comment by andrivet** [comment]
"code cannot complied": what does mean? If you have error messages, please post them.

**Comment by andrivet** [comment]
In fact, your code does not make sense. This is why it does not compile.
Note: I do not provide support to use the library, only for bugs.
