### ISSUE TITLE
Internal compiler error (sometimes)

### ISSUE THREAD

**Issue by AnonymousBOL** [andrivet/ADVobfuscator#3]
VS2015 (v140), internal compiler error if I replace XOR with XOR2.
sprintf_s(szInfoString, XOR("%s = %d"), varName.c_str(), GetInt());
sprintf(szValue, XOR("%.02f"), fltValue);

definitions:
#define XOR(a) a //Place holder to be swapped with XOR2
#define XOR2(a) OBFUSCATED4(a)

I didnt touch any of your code, it's all original.
I tested it separetly and XOR2("%s is %s") works fine (at least compiles, didn't check runtime, but it's not issue) so I guess it's related to sprintf_s/sprintf.

**Comment by andrivet** [comment]
Unfortunately, Visual Studio has several problems with the support of some C++11 features. I will check your example with the latest update and Visual Studio 15 to see if it is better.

**Comment by Amadeus-** [comment]
The issue is sprintf/sprintf_s (https://github.com/andrivet/ADVobfuscator/issues/7)

**Comment by andrivet** [comment]
If I replace the code by:

auto encrypted{ OBFUSCATED4("%s = %d") };
printf_s(szInfoString, encrypted, varName.c_str(), 5);

the Internal compiler error disappears.... Definitely a bug in Visual Studio 2015 compiler.
