### ISSUE TITLE
How to create an array of obfuscated strings?

### ISSUE THREAD

**Issue by vW7JKDTWMGwhRA** [andrivet/ADVobfuscator#36]
In the documentation, could you please clarify how to create an homogeneous array of the obfuscated strings.  

I struggled to eventually be successful with the following.  It does construct an std::vector with all the strings templates having the same key, lengths, and algorithm.  The down-side is that each of these strings will have the same decode keys.
```
std::vector< 
    andrivet::ADVobfuscator::MetaString<0, 0x84, andrivet::ADVobfuscator::Make_Indexes<12>::type>
> string_list = {
    andrivet::ADVobfuscator::MetaString<0, 0x84, andrivet::ADVobfuscator::Make_Indexes<12>::type>("Squirrels\0\0\0")
,   andrivet::ADVobfuscator::MetaString<0, 0x84, andrivet::ADVobfuscator::Make_Indexes<12>::type>("Chipmunks\0")
}
```

**Comment by andrivet** [comment]
No idea of what you are trying to do. And I do not provide support here, unless there is a bug.

**Comment by andrivet** [comment]
Your account is also a fake one. I do not allow thus.
