### ISSUE TITLE
If you can support Visual Studio 2012?

### ISSUE THREAD

**Issue by hoavutinh** [andrivet/ADVobfuscator#4]
I am very interested in this project but I really need it more than in the Visual Studio 2012 build with v110_xp, so I ask you to support this. It would be appreciated.

**Comment by Amadeus-** [comment]
You can see on page 16 of their white paper (which is in the /Docs directory of this project) that Visual Studio 2015 is the first version that supports the features required for this project:

```
This library was developed using Xcode 6.0 and 6.1 beta. The corresponding LLVM version is
3.5. It will however compile and run with any C++11 or C++1y (14) conforming compiler.!
It is currently not compatible with Microsoft Visual C++ including update 3 of Visual Studio 2013
and Visual Studio 2014 CTP3. The main reason is the lack of support of constexpr and of
initialization of arrays. They are only partially supported by Microsoft. 
```

**Comment by andrivet** [comment]
As this project uses C++11 features, it is not possible to support Visual Studio 2012. Only Visual Studio 2015 and Visual Studio 15 are supported.
