### ISSUE TITLE
sprintf/sprintf_s cause Visual Studio 2015 (update 2) compiler crash with OBFUSCATED4()

### ISSUE THREAD

**Issue by Amadeus-** [andrivet/ADVobfuscator#7]
This may be something that you might expect, given that this project utilizes some newer features of C++ (and sprintf, etc. are C functions); however, if there's not a way to fix it, I think it'd be a good idea to include a line about it in this documentation.   sprintf is still used quite a bit, even in C++, and tracking down why this crash was happening was a bit of a pain :)

Anyway, here's the code I used for testing.   Comments included.   Let me know if you have any questions.
```
#include <iostream>
#include <string>
#include "ADVobfuscator\ADVobfuscator\MetaString4.h"
#include <boost/algorithm/string.hpp>
#include <boost/format.hpp>
using namespace andrivet::ADVobfuscator;

int main()
{
	char buf[2048];
	buf[0] = '\0';

	// Enabling this line crashes the compiler!
	//sprintf_s(buf, 2048, OBFUSCATED4("%s %s!\n"), "Hello", "World");

	// Enabling this line also crashes the compiler!
	//sprintf(buf, OBFUSCATED4("%s %s!\n"), "Hello", "World");

	// Compiles and runs just fine
	std::string buf2 = boost::str(boost::format(OBFUSCATED4("%1% %2%!\n")) % "Hello" % "World");
	std::string buf3 = boost::str(boost::format(OBFUSCATED4("%s %s!\n")) % "Hello" % "World");

	std::cout << buf;
	std::cout << buf2;
	std::cout << buf3;
	return 0;
}
```

**Comment by andrivet** [comment]
Visual Studio is not very good and not very stable regarding C++11/14/17 support, unfortunately. I will test myself to see if I can reproduce the problem and if there is a solution.
